### ISSUE TITLE
Add a "related" parameter to the twitter URL

### ISSUE THREAD

**Issue by Benunc** [robincornett/scriptless-social-sharing#2]
Hi Robin!  I was just messing around with your plugin (which is GREAT!) and noticed that you are passing a "via" parameter in the twitter URL, but not a "related" parameter. 

The "related" parameter makes it such that after a person tweets the link, Twitter will recommend that they follow the account. See their documentation here: https://dev.twitter.com/web/tweet-button/web-intent

I have a PR ready to submit that I've tested and seems to work.

**Comment by robincornett** [comment]
That's really interesting, Ben, I did not know that existed. Do you think that's standard enough that everyone would want it by default, and shouldn't be an option?

I think I would prefer to set up the array key without repeating the `$twitter` variable, something like this:

```
'twitter'       => $twitter ? sprintf( '&via=%1$s&related=%1$s', $twitter ) : '',
```

...just a bit picky, but otherwise I'm amenable.

**Comment by Benunc** [comment]
I'm certainly open to that. `sprintf` has always confused me. :-)

Regarding it being standard, I've had it on http://benlikes.us/bctt since almost the beginning, with no complaints yet. I also think that adding it as an option will just confuse the vast majority of folks. I don't see a downside to having twitter recommend me as a good person to follow
